version: 2
updates:
  - package-ecosystem: pip
    directory: /warranty
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - warranty

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
